name: build-release

on:
  workflow_dispatch:
    inputs:
      publish:
        description: "If you want to publish to nuget, set \"publish\"."
        required: false

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build -c Release --output $GITHUB_WORKSPACE/artifacts
    #- name: Test
    #  run: dotnet test --no-build --verbosity normal
    - uses: actions/upload-artifact@v2
      with:
         name: Packages
         path: artifacts
